name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy withbible server
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: yongki150/withbible
          stage: main
          yaml: |-
            name: withbible-server
            app: node@16
            options:
              env:
                - name: TZ
                  value: Asia/Seoul
                - name: LOCAL_HOST
                  value: https://localhost:5000
                - name: CLOUD_HOST
                  value: ${{ vars.CLOUD_HOST }}                
                - name: LOCAL_GUEST
                  value: https://localhost:3000                
                - name: CLOUD_GUEST
                  value: ${{ vars.CLOUD_GUEST }}
                - name: PORT
                  value: 5000
                - name: COOKIE_SECRET
                  value: ${{ secrets.COOKIE_SECRET }}                
                - name: SQL_HOST
                  value: ${{ secrets.SQL_HOST }}
                - name: SQL_USER
                  value: ${{ secrets.SQL_USER }}
                - name: SQL_PASSWORD
                  value: ${{ secrets.SQL_PASSWORD }}
                - name: SQL_PORT
                  value: ${{ secrets.SQL_PORT }}
                - name: SQL_DATABASE
                  value: ${{ secrets.SQL_DATABASE }}
                - name: REDIS_URL
                  value: ${{ secrets.REDIS_URL }}
                - name: GHP_SERVER_ETC_ACCESS_TOKEN
                  value: ${{ secrets.GHP_SERVER_ETC_ACCESS_TOKEN }}
                - name: PUSHER_APP_ID
                  value: ${{ secrets.PUSHER_APP_ID }}
                - name: PUSHER_APP_KEY
                  value: ${{ secrets.PUSHER_APP_KEY }}
                - name: PUSHER_SECREAT
                  value: ${{ secrets.PUSHER_SECREAT }}
                - name: PUSHER_CLUSTER
                  value: ${{ secrets.PUSHER_CLUSTER }}
                - name: PUSHER_BEAMS_INSTANCE_ID
                  value: ${{ secrets.PUSHER_BEAMS_INSTANCE_ID }}
                - name: PUSHER_BEAMS_PRIMARY_KEY
                  value: ${{ secrets.PUSHER_BEAMS_PRIMARY_KEY }}
                - name: SENTRY_DSN_KEY
                  value: ${{ secrets.SENTRY_DSN_KEY }}
                - name: MAX_REQUESTS
                  value: ${{ secrets.MAX_REQUESTS }}
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
      - name: Deploy withbible server cousin
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: yongki150/withbible
          stage: main
          yaml: |-
            name: withbible-server-cousin
            app: node@16
            options:
              env:
                - name: TZ
                  value: Asia/Seoul
                - name: LOCAL_HOST
                  value: https://localhost:5001
                - name: CLOUD_HOST
                  value: ${{ vars.CLOUD_HOST }}                
                - name: LOCAL_GUEST
                  value: https://localhost:3000                
                - name: CLOUD_GUEST
                  value: ${{ vars.CLOUD_GUEST }}
                - name: PORT
                  value: 5001
                - name: COOKIE_SECRET
                  value: ${{ secrets.COOKIE_SECRET }}                
                - name: SQL_HOST
                  value: ${{ secrets.SQL_HOST }}
                - name: SQL_USER
                  value: ${{ secrets.SQL_USER }}
                - name: SQL_PASSWORD
                  value: ${{ secrets.SQL_PASSWORD }}
                - name: SQL_PORT
                  value: ${{ secrets.SQL_PORT }}
                - name: SQL_DATABASE
                  value: ${{ secrets.SQL_DATABASE }}
                - name: REDIS_URL
                  value: ${{ secrets.REDIS_URL }}
                - name: GHP_SERVER_ETC_ACCESS_TOKEN
                  value: ${{ secrets.GHP_SERVER_ETC_ACCESS_TOKEN }}
                - name: PUSHER_APP_ID
                  value: ${{ secrets.PUSHER_APP_ID }}
                - name: PUSHER_APP_KEY
                  value: ${{ secrets.PUSHER_APP_KEY }}
                - name: PUSHER_SECREAT
                  value: ${{ secrets.PUSHER_SECREAT }}
                - name: PUSHER_CLUSTER
                  value: ${{ secrets.PUSHER_CLUSTER }}
                - name: PUSHER_BEAMS_INSTANCE_ID
                  value: ${{ secrets.PUSHER_BEAMS_INSTANCE_ID }}
                - name: PUSHER_BEAMS_PRIMARY_KEY
                  value: ${{ secrets.PUSHER_BEAMS_PRIMARY_KEY }}
                - name: SENTRY_DSN_KEY
                  value: ${{ secrets.SENTRY_DSN_KEY }}
                - name: MAX_REQUESTS
                  value: ${{ secrets.MAX_REQUESTS }}
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
